FROM node:18-alpine as build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# Production stage
FROM nginx:latest-alpine

COPY --from=build-stage /app/dist/your-project-name /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]