            - name: Docker Setup Docker
  # You may pin to the exact commit or the version.
  # uses: docker/setup-docker-action@370a7dad4b8ce8dbf00f9363e1652e5074dd6abe
  uses: docker/setup-docker-action@v4.1.0
  with:
    # Docker CE version. (e.g, v24.0.9)
    version: # optional, default is latest
    # Docker CE channel. (e.g, stable, edge or test)
    channel: # optional
    # Docker daemon JSON configuration
    daemon-config: # optional
    # TCP port to expose the Docker API locally
    tcp-port: # optional
    # Docker context name. (default setup-docker-action)
    context: # optional
    # Set DOCKER_HOST environment variable to docker socket path
    set-host: # optional, default is false
    # Enable Docker rootless mode
    rootless: # optional, default is false
    name: Deploy Client App
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t your-dockerhub-username/client-app:latest .
        docker push your-dockerhub-username/client-app:latest

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@$DEPLOY_SERVER_IP << EOF
        docker pull your-dockerhub-username/client-app:latest
        docker run -d -p 80:80 your-dockerhub-username/client-app:latest
        EOF

  
